### ISSUE TITLE
java.lang.Byte.toUnsignedInt() missing?

### ISSUE THREAD

**Issue by tinloaf** [docbender/openHAB-SimpleBinary#1]
Hi,

I'm using the latest release of the SimpleBinary binding with a current openHAB 1.8.0 from the .deb repository. My system (a raspberry pi) runs oracle java.

Since I upgraded to openHab 1.8.0 (from... 1.7? Not sure...), I'm getting this error and the SimpleBinary binding stopped working:

```
Feb 17 23:47:29 harry openhab.sh[2042]: Exception in thread "SimpleBinary communication service" java.lang.NoSuchMethodError: java.lang.Byte.toUnsignedInt(B)I
Feb 17 23:47:29 harry openhab.sh[2042]: at org.openhab.binding.simplebinary.internal.SimpleBinaryProtocol.arrayToString(SimpleBinaryProtocol.java:680)
Feb 17 23:47:29 harry openhab.sh[2042]: at org.openhab.binding.simplebinary.internal.SimpleBinaryProtocol.evalCRC(SimpleBinaryProtocol.java:657)
Feb 17 23:47:29 harry openhab.sh[2042]: at org.openhab.binding.simplebinary.internal.SimpleBinaryProtocol.compileNewDataFrame(SimpleBinaryProtocol.java:52)
Feb 17 23:47:29 harry openhab.sh[2042]: at org.openhab.binding.simplebinary.internal.SimpleBinaryUART.sendNewDataCheck(SimpleBinaryUART.java:345)
Feb 17 23:47:29 harry openhab.sh[2042]: at org.openhab.binding.simplebinary.internal.SimpleBinaryUART.checkNewData(SimpleBinaryUART.java:929)
Feb 17 23:47:30 harry openhab.sh[2042]: at org.openhab.binding.simplebinary.internal.SimpleBinaryBinding.execute(SimpleBinaryBinding.java:233)
Feb 17 23:47:30 harry openhab.sh[2042]: at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:156)
Feb 17 23:47:30 harry openhab.sh[2042]: at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173)
```

I don't know Java very well, but that looks really strange. I'm pretty certain that java.lang.Byte.toUnsignedInt() exists?

**Comment by docbender** [comment]
Hi, latest version of binding was compiled around 14 days before openHAB 1.8
 was released. I did not test it with openHAB 1.8. 

But it look like Java problem. From log U posted I can see that it crash in 
trace function that prints packet to log file. So in the worst case, can I 
delete it or I can catch this exception.

Now I look into Java documentation and I see that this function is supported
from Java 1.8. Do you have installed Java 1.8?

However I look on it and let you know

---------- Původní zpráva ----------
Od: tinloaf notifications@github.com
Komu: docbender/openHAB-SimpleBinary <openHAB-SimpleBinary@noreply.github.
com>
Datum: 17. 2. 2016 23:51:22
Předmět: [openHAB-SimpleBinary] java.lang.Byte.toUnsignedInt() missing? (#1)

"

Hi,

I'm using the latest release of the SimpleBinary binding with a current 
openHAB 1.8.0 from the .deb repository. My system (a raspberry pi) runs 
oracle java.

Since I upgraded to openHab 1.8.0 (from... 1.7? Not sure...), I'm getting 
this error and the SimpleBinary binding stopped working:

 Feb 17 23:47:29 harry openhab.sh[2042]: Exception in thread "SimpleBinary communication service" java.lang.NoSuchMethodError: java.lang.Byte.toUnsignedInt(B)I
Feb 17 23:47:29 harry openhab.sh[2042]: at org.openhab.binding.simplebinary.internal.SimpleBinaryProtocol.arrayToString(SimpleBinaryProtocol.java:680)
Feb 17 23:47:29 harry openhab.sh[2042]: at org.openhab.binding.simplebinary.internal.SimpleBinaryProtocol.evalCRC(SimpleBinaryProtocol.java:657)
Feb 17 23:47:29 harry openhab.sh[2042]: at org.openhab.binding.simplebinary.internal.SimpleBinaryProtocol.compileNewDataFrame(SimpleBinaryProtocol.java:52)
Feb 17 23:47:29 harry openhab.sh[2042]: at org.openhab.binding.simplebinary.internal.SimpleBinaryUART.sendNewDataCheck(SimpleBinaryUART.java:345)
Feb 17 23:47:29 harry openhab.sh[2042]: at org.openhab.binding.simplebinary.internal.SimpleBinaryUART.checkNewData(SimpleBinaryUART.java:929)
Feb 17 23:47:30 harry openhab.sh[2042]: at org.openhab.binding.simplebinary.internal.SimpleBinaryBinding.execute(SimpleBinaryBinding.java:233)
Feb 17 23:47:30 harry openhab.sh[2042]: at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:156)
Feb 17 23:47:30 harry openhab.sh[2042]: at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173)

I don't know Java very well, but that looks really strange. I'm pretty 
certain that java.lang.Byte.toUnsignedInt() exists?

—
Reply to this email directly or view it on GitHub
(https://github.com/docbender/openHAB-SimpleBinary/issues/1). 

"=

**Comment by docbender** [comment]
Hi,

I replace toUnsignedInt  function in binding code. You can try new version 
here: 

https://github.com/docbender/openHAB-SimpleBinary/releases/download/0.3.2/
org.openhab.binding.simplebinary_1.8.0.201602181314.jar

---------- Původní zpráva ----------
Od: tinloaf notifications@github.com
Komu: docbender/openHAB-SimpleBinary <openHAB-SimpleBinary@noreply.github.
com>
Datum: 17. 2. 2016 23:51:22
Předmět: [openHAB-SimpleBinary] java.lang.Byte.toUnsignedInt() missing? (#1)

"

Hi,

I'm using the latest release of the SimpleBinary binding with a current 
openHAB 1.8.0 from the .deb repository. My system (a raspberry pi) runs 
oracle java.

Since I upgraded to openHab 1.8.0 (from... 1.7? Not sure...), I'm getting 
this error and the SimpleBinary binding stopped working:

 Feb 17 23:47:29 harry openhab.sh[2042]: Exception in thread "SimpleBinary communication service" java.lang.NoSuchMethodError: java.lang.Byte.toUnsignedInt(B)I
Feb 17 23:47:29 harry openhab.sh[2042]: at org.openhab.binding.simplebinary.internal.SimpleBinaryProtocol.arrayToString(SimpleBinaryProtocol.java:680)
Feb 17 23:47:29 harry openhab.sh[2042]: at org.openhab.binding.simplebinary.internal.SimpleBinaryProtocol.evalCRC(SimpleBinaryProtocol.java:657)
Feb 17 23:47:29 harry openhab.sh[2042]: at org.openhab.binding.simplebinary.internal.SimpleBinaryProtocol.compileNewDataFrame(SimpleBinaryProtocol.java:52)
Feb 17 23:47:29 harry openhab.sh[2042]: at org.openhab.binding.simplebinary.internal.SimpleBinaryUART.sendNewDataCheck(SimpleBinaryUART.java:345)
Feb 17 23:47:29 harry openhab.sh[2042]: at org.openhab.binding.simplebinary.internal.SimpleBinaryUART.checkNewData(SimpleBinaryUART.java:929)
Feb 17 23:47:30 harry openhab.sh[2042]: at org.openhab.binding.simplebinary.internal.SimpleBinaryBinding.execute(SimpleBinaryBinding.java:233)
Feb 17 23:47:30 harry openhab.sh[2042]: at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:156)
Feb 17 23:47:30 harry openhab.sh[2042]: at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173)

I don't know Java very well, but that looks really strange. I'm pretty 
certain that java.lang.Byte.toUnsignedInt() exists?

—
Reply to this email directly or view it on GitHub
(https://github.com/docbender/openHAB-SimpleBinary/issues/1). 

"=

**Comment by tinloaf** [comment]
Works like a charm, thank you very much!

But it is _really_ strange that that method seems to be missing...
